### ISSUE TITLE
getting `recyclerView must not be null` exception when using Fragment

### ISSUE THREAD

**Issue by stvalentin** [TheJuki/KFormMaster#28]
hey I'm trying to use your plugin inside a tab view,  just that on each 3.x version that I tested so far i'm getting the same error:

```
/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.maustudios.android, PID: 4330
                  java.lang.IllegalStateException: recyclerView must not be null
                      at com.maustudios.android.AppointmentFragment.setupForm(AppointmentFragment.kt:52)
                      at com.maustudios.android.AppointmentFragment.onCreateView(AppointmentFragment.kt:66)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Application terminated.
```

```
class AppointmentFragment : Fragment() {
    private lateinit var formBuilder: FormBuildHelper

    private enum class Tag {
        Email,
        Password
    }

    private fun setupForm() {

        val listener = object : OnFormElementValueChangedListener {
            override fun onValueChanged(formElement: BaseFormElement<*>) {

            }
        }

        formBuilder = form(this.context!!, recyclerView, listener, true) {
            header { title = getString(R.string.email) }
            email(Tag.Email.ordinal) {
                title = getString(R.string.email)
                hint = getString(R.string.email)
            }
            password(Tag.Password.ordinal) {
                title = getString(R.string.password)
            }
        }
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val view = inflater.inflate(R.layout.appointment_fragment, container, false)
        this.setupForm();
        return view;
    }


    companion object {
        fun newInstance(): AppointmentFragment = AppointmentFragment()
    }
}
```

**Comment by TheJuki** [comment]
Not sure if this is a bug. I would need to see your imports. 

recyclerView should come from your appointment_fragment layout using kotlin extensions.

Such as: import kotlinx.android.synthetic.main.appointment_fragment.*

**Comment by TheJuki** [comment]
Actually...Fragments are weird. You would need to pass the view.recyclerView to setupForm().

```
class AppointmentFragment : Fragment() {
    private lateinit var formBuilder: FormBuildHelper

    private enum class Tag {
        Email,
        Password
    }

    private fun setupForm(recyclerView: RecyclerView) {

        val listener = object : OnFormElementValueChangedListener {
            override fun onValueChanged(formElement: BaseFormElement<*>) {

            }
        }

        formBuilder = form(this.context!!, recyclerView, listener, true) {
            header { title = getString(R.string.email) }
            email(Tag.Email.ordinal) {
                title = getString(R.string.email)
                hint = getString(R.string.email)
            }
            password(Tag.Password.ordinal) {
                title = getString(R.string.password)
            }
        }
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val view = inflater.inflate(R.layout.appointment_fragment, container, false)
        this.setupForm(view.recyclerView);
        return view;
    }


    companion object {
        fun newInstance(): AppointmentFragment = AppointmentFragment()
    }
}
```

**Comment by stvalentin** [comment]
Hi @TheJuki 
Thank you, that was the issue, still new to android development

**Comment by khalidsophee** [comment]
You can deal with this issue by removing explicit casting of recyclerview , and let the Android Studio do its implicit Casting.
val rec = findViewById<RecyclerView>(R.id.userrecyclerview)
