### ISSUE TITLE
5.0.2 broken

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#59]
Hi there,

I can not update my kForm build gradle version anymore. I tried to update from 5.0.0 to 5.0.2 and got some error messages.

It seems like all classes of the library are gone.

- Unresolved Reference: helper
- Unresolved Reference: model

I'm using Android Studio 3.2

Example:

> Could not find class data for nested class com/thejuki/kformmaster/widget/SegmentedGroup.LayoutSelector of class com/thejuki/kformmaster/widget/SegmentedGroup
> Root file: /Users/.../.gradle/caches/transforms-1/files-1.1/k-form-master-5.0.2.aar/a1c0010187862f3d2796bea8a126f8dc/jars/classes.jar!/com/thejuki/kformmaster/widget/SegmentedGroup.class
> Dir: /Users/.../.gradle/caches/transforms-1/files-1.1/k-form-master-5.0.2.aar/a1c0010187862f3d2796bea8a126f8dc/jars/classes.jar!/com/thejuki/kformmaster/widget
> Children:
> ClearableEditText$a.class (valid: true)
> ClearableEditText$b.class (valid: true)
> ClearableEditText.class (valid: true)
> SegmentedGroup$a.class (valid: true)
> SegmentedGroup$b.class (valid: true)
> SegmentedGroup.class (valid: true)
> java.lang.Throwable: Could not find class data for nested class com/thejuki/kformmaster/widget/SegmentedGroup.LayoutSelector of class com/thejuki/kformmaster/widget/SegmentedGroup
> Root file: /Users/.../.gradle/caches/transforms-1/files-1.1/k-form-master-5.0.2.aar/a1c0010187862f3d2796bea8a126f8dc/jars/classes.jar!/com/thejuki/kformmaster/widget/SegmentedGroup.class
> Dir: /Users/.../.gradle/caches/transforms-1/files-1.1/k-form-master-5.0.2.aar/a1c0010187862f3d2796bea8a126f8dc/jars/classes.jar!/com/thejuki/kformmaster/widget
> Children:
> ClearableEditText$a.class (valid: true)
> ClearableEditText$b.class (valid: true)
> ClearableEditText.class (valid: true)
> SegmentedGroup$a.class (valid: true)
> SegmentedGroup$b.class (valid: true)
> SegmentedGroup.class (valid: true)
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
> 	at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.createNestedClassStub(ClassClsStubBuilder.kt:253)
> 	at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.createInnerAndNestedClasses(ClassClsStubBuilder.kt:244)
> 	at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.createClassBodyAndMemberStubs(ClassClsStubBuilder.kt:187)
> 	at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilder.build(ClassClsStubBuilder.kt:96)
> 	at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClassClsStubBuilderKt.createClassStub(ClassClsStubBuilder.kt:55)
> 	at org.jetbrains.kotlin.idea.decompiler.stubBuilder.ClsStubBuildingKt.createTopLevelClassStub(clsStubBuilding.kt:53)
> 	at org.jetbrains.kotlin.idea.decompiler.classFile.KotlinClsStubBuilder.doBuildFileStub(KotlinClsStubBuilder.kt:86)
> 	at org.jetbrains.kotlin.idea.decompiler.classFile.KotlinClsStubBuilder.buildFileStub(KotlinClsStubBuilder.kt:52)
> 	at com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:45)
> 	at com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:25)
> 	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:61)
> 	at com.intellij.psi.stubs.StubUpdatingIndex$3.lambda$map$0(StubUpdatingIndex.java:232)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:897)
> 	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:214)
> 	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:197)
> 	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:273)
> 	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:96)
> 	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:213)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1687)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$21(FileBasedIndexImpl.java:1615)
> 	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:523)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1574)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1562)
> 	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:116)
> 	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:230)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
> 	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:246)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
> 	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:243)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by darkwood-studios** [comment]
Edit:
5.0.1 is not working, too. Any critical changes there? 5.0.0 is working without problems.

**Comment by TheJuki** [comment]
I removed version 5.0.1 and 5.0.2 from Bintray. I left minifyEnabled enabled for the release build and was causing that issue. Please use version 5.0.3.
