### ISSUE TITLE
Problem while adding FormPickerMultiCheckBoxElement

### ISSUE THREAD

**Issue by shubhral** [TheJuki/KFormMaster#84]
## Description
My application is written in Java. I'm adding a Multi select checkbox like this (copied from your github java example)
```
androidx.recyclerview.widget.RecyclerView.RecyclerView recyclerView = findViewById(R.id.dynamic_form_rv);
        FormLayouts formLayouts = new FormLayouts();
        FormBuildHelper formBuilder = new FormBuildHelper(this, this, recyclerView, true, formLayouts);
        List<BaseFormElement<?>> elements = new ArrayList<>();
        
        elements.add(new FormHeader("Multi select"));
        FormPickerMultiCheckBoxElement<List<ListItem>> multiCheckBox = new 
        FormPickerMultiCheckBoxElement<>(Tag.MultiItems.ordinal());
        multiCheckBox.setTitle("title");
        multiCheckBox.setDialogTitle("title");
        multiCheckBox.setOptions(fruits);
        elements.add(multiCheckBox);
        
        formBuilder.addFormElements(elements);
```

While others are elements are working fine, but whenever I add this, it throws an error - 

```
java.lang.ClassCastException: android.support.v7.app.AlertController$RecycleListView cannot be cast to androidx.appcompat.app.AlertController$RecycleListView
        at androidx.appcompat.app.AlertController$AlertParams.createListView(AlertController.java:989)
        at androidx.appcompat.app.AlertController$AlertParams.apply(AlertController.java:965)
        at androidx.appcompat.app.AlertDialog$Builder.create(AlertDialog.java:982)
        at com.thejuki.kformmaster.model.FormPickerMultiCheckBoxElement.reInitDialog(FormPickerMultiCheckBoxElement.kt:152)
        at com.thejuki.kformmaster.view.FormPickerMultiCheckBoxViewBinder$viewBinder$1.bindView(FormPickerMultiCheckBoxViewBinder.kt:47)
        at com.thejuki.kformmaster.view.FormPickerMultiCheckBoxViewBinder$viewBinder$1.bindView(FormPickerMultiCheckBoxViewBinder.kt:26)
        at com.github.vivchar.rendererrecyclerviewadapter.binder.ViewBinder.bindView(ViewBinder.java:80)
        at com.github.vivchar.rendererrecyclerviewadapter.ViewRenderer.performBindView(ViewRenderer.java:63)
        at com.github.vivchar.rendererrecyclerviewadapter.RendererRecyclerViewAdapter.onBindViewHolder(RendererRecyclerViewAdapter.java:89)
        at com.github.vivchar.rendererrecyclerviewadapter.RendererRecyclerViewAdapter.onBindViewHolder(RendererRecyclerViewAdapter.java:30)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
        at android.view.View.measure(View.java:18799)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:18799)
        at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1449)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:515)
        at android.view.View.measure(View.java:18799)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:719)
        at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:789)
        at android.view.View.measure(View.java:18799)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:18799)
```
### Steps to reproduce the bug

1. Add FormPickerMultiCheckBoxElement in androidx.recyclerview
2. Run the app

### KFormMaster version

* 6.1.1

I've followed all the instructions, and have         `maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }` added to root build file as well.

### System information

* Android OS: 6.0.1
* Issue in Emulator: Yes
* Issue in physical device: Yes

**Comment by TheJuki** [comment]
The latest release uses AndroidX. You are still using the support libraries. Upgrade to AndroidX or use version 6.0.0 for now.

https://developer.android.com/jetpack/androidx/
